### PR TITLE
Add Borodutch/telegram-bot-starter

### PR DESCRIPTION
**Pull request by abdoo9**
another bot template.

### CODE REVIEW

**Comment by roj1512** [comment]
@KnorpelSenf I was thinking, should the owner add it themselves?

**Comment by KnorpelSenf** [comment]
@backmeupplz?

**Comment by waptik** [comment]
> @backmeupplz?

I think he doesn't want anything to do with telegram again so i doubt he'll bother to add it himself. I think users can add repos of other authors they find interesting, as most repos owners don't have time or energy to add it themselves

**Comment by KnorpelSenf** [comment]
You're most likely right. I was hoping he still thought fondly of grammY … but he probably moved on indeed. @roj1512 we can just merge, his templates are usually good.

**Review by KnorpelSenf — APPROVED** [review]

**Review by roj1512 — APPROVED** [review]
OK!

**Pull request merged**
