### PR TITLE
Added @AnyVideoDownloadBot to the open-source list

### PR DESCRIPTION
**Pull request by backmeupplz**

### CODE REVIEW

**Review by rojserbest — APPROVED** [review]

**Review by KnorpelSenf — COMMENTED** [review]
The URL is dysfunctional. Please fix this.

**Comment by rojserbest** [comment]
A

**Comment by rojserbest** [comment]
I merged this on my phone

**Comment by rojserbest** [comment]
@KnorpelSenf I fixed it!

**Pull request merged**
