### PR TITLE
add a template to deploy to railway

### PR DESCRIPTION
**Pull request by waptik**
This template was created in hopes of providing some form of guidance for those who want to deploy their bots on [Railway](https://waptik.vercel.app/railway). See original post on [telegram group](https://t.me/grammyjs/90976)

### CODE REVIEW

**Comment by waptik** [comment]
Sorry for the bad grammar in the second commit!!!

**Comment by KnorpelSenf** [comment]
Please wait for a review, rather than merging your own unreviewed pull requests.

Shouldn't this go into the example bots repository instead?

**Comment by waptik** [comment]
Sorry for the merger of the unreviewed PR.
I thought I'd put it in here since similar templates were found here. Is it because the repo hasn't been changed to a template repo yet?

But if you think it should be in the examples repo then I'll put it there.

**Comment by KnorpelSenf** [comment]
It's not a should, I was asking a question. We already have vercel templates in the example bots repo. I feel like this ought to be unified. @roj1512 what's your opinion?

**Comment by waptik** [comment]
I understand. If so we should move the template for deta there as well.

**Comment by roj1512** [comment]
@waptik Create another PR.

**Comment by roj1512** [comment]
@KnorpelSenf We'll work on that in the next PQ related to this.

**Comment by roj1512** [comment]
@waptik You can also re-open this PR since you haven't deleted the branch.

**Comment by KnorpelSenf** [comment]
Sounds great!

**Comment by waptik** [comment]
> @waptik Create another PR.

In the example bots repo or here?

**Comment by waptik** [comment]
> @waptik Create another PR.

In the example bots repo or here?

**Pull request merged**
